Import('env')
local_env = env.Clone()
local_env.Append(CPPPATH='.')
objects = []
for c in Glob('*.c') + Glob('*.cpp') + Glob('*.S'):
    objects.append(local_env.StaticObject('${SOURCE.file}${OBJSUFFIX}', c))
local_env.StaticLibrary('core', objects)
