Import('env')
local_env = env.Clone()
local_env.Append(LIBPATH=['../arduino'],
                 CPPPATH=['../arduino'],
                 LIBS=['core_c', 'core_cpp', 'core_S'])
local_env.StaticLibrary('main.cpp')
