Import('env')
local_env = env.Clone()

# Collect Our Source to Build
sources = [source for pattern in [
    '*.c', '*.cpp', '*.S'] for source in Glob(pattern)]

# Core Arduino Library Includes
local_env.Append(LIBPATH=['../arduino'],
                 CPPPATH=['../arduino', '.', 'utility'])

# Build Object Files
objects = []
for source in sources:
    if source.abspath.lower().endswith('.c'):
        objects.append(local_env.Command('${SOURCE.file}${OBJSUFFIX}', source,
                                         '${recipe_c_o_pattern}',
                                         source_file='${SOURCE}',
                                         object_file='${TARGET}'))
    elif source.abspath.lower().endswith('.cpp'):
        objects.append(local_env.Command('${SOURCE.file}${OBJSUFFIX}', source,
                                         '${recipe_cpp_o_pattern}',
                                         source_file='${SOURCE}',
                                         object_file='${TARGET}'))
    elif source.abspath.lower().endswith('.s'):
        objects.append(local_env.Command('${SOURCE.file}${OBJSUFFIX}', source,
                                         '${recipe_S_o_pattern}',
                                         source_file='${SOURCE}',
                                         object_file='${TARGET}'))
    else:
        print('I do not know how to build specified source file: %s' % source)

# Append the Arduino Library to the List of Objects
objects.append(File('../arduino/libcore.a'))

elf = local_env.Command(
    'target.elf', objects,
    '${recipe_c_combine_pattern}',
    recipe_c_combine_pattern=local_env['recipe_c_combine_pattern'].replace(
        '"${build_path}/${archive_file}"', '').replace('.elf', ''),
    object_files='${SOURCES}')
eep = local_env.Command(
    'target.eep', elf,
    '${recipe_objcopy_eep_pattern}',
    recipe_objcopy_eep_pattern=local_env['recipe_objcopy_eep_pattern'].replace(
        '.eep', '').replace('"${build_path}/${build_project_name}.elf"',
                            '${SOURCE}'))
hex = local_env.Command(
    'target.hex', elf,
    '${recipe_objcopy_hex_pattern}',
    recipe_objcopy_hex_pattern=local_env['recipe_objcopy_hex_pattern'].replace(
        '.hex', '').replace('"${build_path}/${build_project_name}.elf"',
                            '${SOURCE}'))

bin = local_env.Command(
    'upload', hex,
    'echo ${tools_avrdude_upload_pattern} > ${TARGET}',
    cmd_path='${tools_avrdude_cmd_path}',
    config_path='${tools_avrdude_config_path}',
    tools_avrdude_upload_pattern=local_env['tools_avrdude_upload_pattern'].replace(
        '${build_path}/${build_project_name}.hex', '${SOURCE}'))
Return('bin')
